Count,Message,Traceback,Nodes
16,exceptions must derive from BaseException,"  File ""E:\Install_Software\python\lib\site-packages\locust\user\task.py"", line 296, in run
    self.execute_next_task()
  File ""E:\Install_Software\python\lib\site-packages\locust\user\task.py"", line 321, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""E:\Install_Software\python\lib\site-packages\locust\user\task.py"", line 333, in execute_task
    task(self)
  File ""H:\Locust_Concurrent_v4\locust_AB\test_reg_user_stress.py"", line 56, in test_reg_user_stress
    raise ""IndexError: list index out of range!""
",local
